### ISSUE TITLE
Adding a new container allows duplicate name

### ISSUE THREAD

**Issue by cicorias** [azure-storage/deco#297]
Chose to add container put in a lower case ~ 8 character string and saved.

The message logs in the bottom pane indicated created. Is the view of containers perhaps cached

![2015-09-07_21-39-04](https://cloud.githubusercontent.com/assets/1080406/9724647/fdeac724-55a8-11e5-99a8-1a0b136053be.png)

Clicking refresh logs doesn't change result

Even though the image shows the success of a /paceedu and paceedu - i also added another pacedu that shows up in the left container list

**Comment by sedouard** [comment]
Thanks @cicorias for testing these scenarios out. I'll break this issue up into two parts.

- Adding a duplicate container is successful. 

This is caused by the fact that [we use `crateContainerIfNotExists`](https://github.com/azure-storage/xplat/blob/master/app/adapters/container.js#L71), when really, we should use [`createContainer`](https://github.com/Azure/azure-storage-node/blob/master/lib/services/blob/blobservice.js#L408) instead. This will cause the promise the resolve as an error causing an error message to show up, rather than a successful container addition.

- Creating a container with an invalid name is successful.

We need to propagate the exception [here](https://github.com/azure-storage/xplat/blob/master/app/adapters/container.js#L78). The UI is setup to handle catches and display the api error by default. In general we probably should do this for all of our promise catch handlers within the adapters.

**Comment by sedouard** [comment]
Also added [this issue](https://github.com/azure-storage/xplat/issues/300) since its related to the second item noted above.
